version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    
  # Optional: Add a database if needed in the future
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: mergington
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
